/** Mock desk data — replace or merge from hydration bundle.ai_compute */
window.WMC_DATA = {
  meta: {
    version: '1.1.0',
    as_of: '2026-07-04',
    build: 'WMC-MODULAR-2026-07-04-PHASE23',
    thesis: 'Midwest compute crush: H200 fwd contango + MISO Indiana Hub power drag + BTC high-beta transmission gate.',
  },
  kpis: [
    { label: 'GPU Basis (H200)', value: '0.14', unit: '$/hr', delta: '+0.06', dir: 'up', hero: false },
    { label: 'MISO Indiana RT', value: '38.6', unit: '$/MWh', delta: '+2.4', dir: 'up', hero: false },
    { label: 'Crush P&L Est.', value: '+6.4', unit: '%', delta: '45d horizon', dir: 'up', hero: true },
    { label: 'Net Exposure', value: '1.8', unit: 'x NAV', delta: 'within limit', dir: 'flat', hero: false },
    { label: 'Transmission Gate', value: 'PROBE', unit: '', delta: 'layer2 cap', dir: 'flat', hero: false },
  ],
  basis_tracker: [
    { leg: 'H200 Spot Rental', compute: 4.12, miso_power: 38.6, hy_gas: 2.84, hg_copper: 4.52, btc_basis: 0.082, z_score: 1.2, dislocation: 'fair' },
    { leg: 'H200 3M Fwd', compute: 4.78, miso_power: 36.2, hy_gas: 2.91, hg_copper: 4.48, btc_basis: 0.095, z_score: 0.8, dislocation: 'fair' },
    { leg: 'H100 Spot Rental', compute: 3.48, miso_power: 38.6, hy_gas: 2.84, hg_copper: 4.52, btc_basis: 0.082, z_score: -0.3, dislocation: 'cheap' },
    { leg: 'Crush Spread (3M−Spot)', compute: 0.66, miso_power: -2.4, hy_gas: 0.07, hg_copper: -0.04, btc_basis: 0.013, z_score: 2.4, dislocation: 'rich' },
    { leg: 'Power Basis (DA−RT)', compute: null, miso_power: -3.4, hy_gas: null, hg_copper: null, btc_basis: null, z_score: -1.8, dislocation: 'cheap' },
    { leg: 'BTC Basis (CME)', compute: null, miso_power: null, hy_gas: null, hg_copper: null, btc_basis: 0.082, z_score: 2.9, dislocation: 'extreme' },
    { leg: 'HYG/LQD RV', compute: null, miso_power: null, hy_gas: 312, hg_copper: null, btc_basis: null, z_score: 1.6, dislocation: 'rich' },
    { leg: 'Nat Gas (Henry Hub)', compute: null, miso_power: null, hy_gas: 2.84, hg_copper: null, btc_basis: null, z_score: 0.4, dislocation: 'fair' },
  ],
  trade_variants: {
    core: {
      name: 'Core',
      posture: 'watch',
      signal: 'Long 3M H200 fwd · Short spot rental',
      signal_dir: 'long',
      sizing: '0.75x book cap',
      stop: '-3.2% basis widening',
      target: '+6.4% crush convergence',
      rationale: 'Spot/fwd contango at 0.66 $/hr with MISO power stable. Highbeta layer2 capped at PROBE — size down until BTC transmission clears.',
    },
    curve: {
      name: 'Curve',
      posture: 'execute',
      signal: 'Steepener: long 6M / short 1M GPU fwd',
      signal_dir: 'long',
      sizing: '0.5x curve sleeve',
      stop: 'Curve flatten < 0.15 $/hr',
      target: '+4.2% roll yield capture',
      rationale: '6M/1M spread at 0.57 $/hr vs 90d avg 0.38. Power seasonality supports deferred capacity premium through Q4.',
    },
    basis: {
      name: 'Basis',
      posture: 'watch',
      signal: 'Fade BTC basis richness vs GPU rental',
      signal_dir: 'short',
      sizing: '0.25x basis sleeve',
      stop: 'BTC basis > 12%',
      target: 'Reversion to 5% implied',
      rationale: 'BTC CME basis at 8.2% (Z=2.9) while GPU basis compressing. Cross-asset dislocation — wait for highbeta gate upgrade.',
    },
    seasonal: {
      name: 'Seasonal',
      posture: 'pass',
      signal: 'MISO summer peak power long · GPU short overlay',
      signal_dir: 'neutral',
      sizing: '0x (deferred)',
      stop: 'RT LMP < $28/MWh',
      target: '+$8/MWh peak capture',
      rationale: 'Jul–Aug Indiana Hub peak historically +18% vs DA. GPU inference seasonality flat — no expression until Aug power curve confirms.',
    },
    risk_on_off: {
      name: 'Risk-On/Off',
      posture: 'watch',
      signal: 'Risk-off: long HYG RV · short BTC beta overlay',
      signal_dir: 'long',
      sizing: '0.4x macro sleeve',
      stop: 'HY OAS < 280bps',
      target: '+45bps spread tightening',
      rationale: 'Credit RV rich (Z=1.6) with GPU crush uncorrelated to HY. Risk-off regime favors credit long vs BTC short hedge on compute book.',
    },
    credit_rv: {
      name: 'Credit RV HY/IG',
      posture: 'execute',
      signal: 'Long HYG · Short LQD · Flat GPU',
      signal_dir: 'long',
      sizing: '1.0x credit RV cap',
      stop: '-25bps spread widening',
      target: '+40bps convergence',
      rationale: 'HYG/LQD at 312bps vs 280bps fair value. Independent of compute crush — run as parallel sleeve with shared VaR budget.',
    },
  },
  risk_summary: {
    correlation: {
      labels: ['GPU', 'MISO', 'HYG', 'HG', 'BTC'],
      matrix: [
        [1.00, 0.42, -0.18, 0.31, 0.67],
        [0.42, 1.00, 0.12, 0.28, 0.15],
        [-0.18, 0.12, 1.00, 0.55, -0.22],
        [0.31, 0.28, 0.55, 1.00, 0.08],
        [0.67, 0.15, -0.22, 0.08, 1.00],
      ],
    },
    var: [
      { bucket: 'GPU Compute', var: 124000, cvar: 158000, limit: 200000, util: 0.62 },
      { bucket: 'MISO Power', var: 48000, cvar: 62000, limit: 100000, util: 0.48 },
      { bucket: 'Credit RV', var: 86000, cvar: 112000, limit: 150000, util: 0.57 },
      { bucket: 'BTC Basis', var: 95000, cvar: 128000, limit: 120000, util: 0.79 },
      { bucket: 'Portfolio Net', var: 198000, cvar: 245000, limit: 350000, util: 0.57 },
    ],
    net_exposure: [
      { leg: 'GPU Compute', value: 0.75, direction: 'long' },
      { leg: 'MISO Power', value: 0.20, direction: 'long' },
      { leg: 'Credit RV', value: 1.00, direction: 'long' },
      { leg: 'BTC Hedge', value: 0.35, direction: 'short' },
      { leg: 'Copper', value: 0.10, direction: 'long' },
    ],
    net_total: 1.8,
    net_limit: 2.5,
  },
  chart_placeholders: [
    { title: 'GPU Forward Curve', desc: 'H200 spot vs 1M/3M/6M/12M forwards', wtc_hash: '#ai-compute', panel: 'aiChartFwdCurve' },
    { title: 'Crush Trade P&L', desc: 'GPU futures vs BTC basis transmission', wtc_hash: '#ai-compute', panel: 'aiChartCrushTrade' },
    { title: 'MISO Indiana Hub LMP', desc: 'RT vs DA power basis overlay', wtc_hash: '#ai-compute', panel: 'aiChartMiso' },
    { title: 'Basis vs BTC', desc: 'GPU rental basis vs BTC 1W returns', wtc_hash: '#ai-compute', panel: 'aiChartBasisBtc' },
    { title: 'Vol Surface', desc: 'GPU capacity implied vol grid', wtc_hash: '#ai-compute', panel: 'aiChartVol' },
    { title: 'Credit RV Monitor', desc: 'HYG/LQD spread vs transmission gate', wtc_hash: '#corporate-credit', panel: 'creditRvPanel' },
  ],
  sources: {
    barchart: { label: 'Barchart Watchlist', url: 'https://www.barchart.com/my/watchlist', field: 'gpu_futures, hg_copper, nat_gas' },
    koyfin: { label: 'Koyfin Watchlist (/myw/)', url: 'https://app.koyfin.com/myw/', field: 'HYG, LQD, BTC basis proxy' },
    miso_api: { label: 'MISO Indiana Hub API', url: 'https://api.misoenergy.org/MISORTWDDataBroker/', field: 'MISO.INDIANA.HUB RT/DA LMP' },
    silicon_data: { label: 'Silicon Data GPU Index', url: 'https://silicondata.com/', field: 'H100/H200 rental $/hr spot & fwd' },
    cmegroup: { label: 'CME BTC Basis', url: 'https://www.cmegroup.com/markets/cryptocurrencies/', field: 'BTC futures basis & implied rate' },
    hydration: { label: 'WTC Hydration Bundle', url: './data/hydration/latest.json', field: 'ai_compute, corporate_credit blocks' },
  },
  explainer: {
    title: 'Understanding the Midwest Compute Crush',
    components: {
      title: 'Core components & mechanics',
      intro: 'The Midwest Compute Crush is a cross-asset basis trade that expresses GPU capacity economics against Midwest power, energy inputs, and high-beta transmission overlays.',
      items: [
        { leg: 'GPU spot rental', detail: 'H200/H100 $/hr spot index — the cash cost of immediate inference capacity (desk: 4.12 $/hr H200 spot).' },
        { leg: 'GPU forward rental', detail: 'Deferred capacity curve (1M/3M/6M) — captures delivery premium and contango (desk: 4.78 $/hr H200 3M fwd).' },
        { leg: 'MISO Indiana Hub power', detail: 'RT vs DA LMP — Midwest merchant power drag on colocated GPU farms (desk: 38.6 $/MWh RT).' },
        { leg: 'Henry Hub nat gas', detail: 'Marginal fuel input for Midwest generation stack; feeds power basis seasonality (desk: 2.84 $/MMBtu).' },
        { leg: 'HG copper', detail: 'Infra capex signal for interconnect and rack build-out; correlated with power/compute expansion cycles.' },
        { leg: 'BTC CME basis', detail: 'High-beta transmission gate — when basis is rich (Z>2), layer2 sizing caps crush expression.' },
        { leg: 'Crush spread', detail: 'Fwd_GPU − Spot_GPU — the core arb leg; desk crush spread at 0.66 $/hr (3M−Spot), Z=2.4 rich.' },
      ],
    },
    drivers: {
      title: 'Key economic drivers',
      items: [
        'Midwest summer peak power (Jul–Aug): Indiana Hub RT historically +18% vs DA — raises power-adjusted crush cost.',
        'GPU fwd contango/backwardation: hyperscaler capex cycles flatten or steepen the deferred capacity premium.',
        'Spot rental liquidity gaps: fragmented spot markets (Vast.ai, Lambda) widen basis vs institutional fwd quotes.',
        'Credit RV overlay (HYG/LQD): risk-off tightens HY spreads independently of compute — parallel sleeve, shared VaR.',
        'BTC high-beta gate: GPU–BTC correlation ~0.67 (30D); rich BTC basis blocks layer2 sizing until transmission clears.',
        'Nat gas–power pass-through: Henry Hub moves feed MISO marginal cost; β_power sensitivity med on desk default.',
      ],
    },
    formulas: [
      {
        name: 'Crush Spread',
        expression: 'Crush Spread ($/hr) = Fwd_GPU − Spot_GPU',
        note: 'Desk example: 4.78 − 4.12 = 0.66 $/hr (3M H200 fwd minus spot).',
      },
      {
        name: 'Crush Margin',
        expression: 'Crush Margin ($/hr) = Crush Spread − Power_Adj',
        note: 'Power_Adj ($/hr) = β_power × (MISO_RT − MISO_DA) / 1000 × kW_per_GPU. β_power maps to gpu_power_sensitivity (low/med/high).',
      },
      {
        name: 'Basis P&L',
        expression: 'Basis P&L (%) = (Entry_Basis − Current_Basis) × 100',
        note: 'Desk crush trade: entry 0.22 → current 0.08 → implied +14% basis capture; expected P&L +6.4% at 45d horizon.',
      },
      {
        name: 'Sensitivity P&L',
        expression: 'Sensitivity P&L (%) = (Entry − Current) × (1 + Shock%) × 100',
        note: 'Mirrors WTC ai_compute crush sim slider — shock widens or compresses basis convergence path.',
      },
    ],
    sensitivity: {
      title: 'Sensitivity & scenarios',
      scenarios: [
        { label: 'Power +$5/MWh RT shock', impact: 'Crush margin −0.04 to −0.08 $/hr (med β_power); favors short power overlay in summer.' },
        { label: 'GPU fwd +0.10 $/hr', impact: 'Crush spread widens +0.10 $/hr; rich dislocation deepens — fade or scale into convergence.' },
        { label: 'BTC basis +200bps', impact: 'High-beta gate tightens; layer2 cap stays PROBE — reduce crush sleeve to 0.5x.' },
        { label: 'Summer peak (Jul–Aug)', impact: 'MISO RT premium expands; seasonal expression deferred until DA curve confirms (+$8/MWh target).' },
        { label: 'Risk-off (HY OAS widen)', impact: 'Credit RV sleeve benefits (+45bps target); GPU crush uncorrelated — run parallel book.' },
        { label: 'Hyperscaler capex cut', impact: 'Fwd curve flattens; crush spread compresses — invalidates long fwd / short spot core.' },
      ],
    },
    risks: {
      title: 'Risk factors & pitfalls',
      items: [
        'Delivery slippage on forward GPU contracts — fwd quote may not translate to physical capacity at settlement.',
        'BTC high-beta decoupling breaks basis hedge — correlation spike can flip sign under liquidity stress.',
        'Hyperscaler capex cuts flatten forward curve — crush spread mean-reverts faster than horizon assumes.',
        'Regulatory export controls on H100/H200 clusters — basis dislocates on supply shock, not convergence.',
        'MISO power basis blowouts (DA−RT) — negative power basis (desk: −3.4) masks true merchant cost drag.',
        'Over-sizing through transmission gate — PROBE layer2 cap requires 0.75x book cap max on core crush.',
        'Spot market liquidity gaps — Vast.ai / spot indices gap on weekends; fwd marks stale relative to spot.',
        'Cross-asset false convergence — GPU basis compressing while BTC basis rich (Z=2.9) signals non-stationary pair.',
      ],
    },
  },
  corporate_comps: {
    crush_operators: [
      { name: 'CoreWeave', ticker: 'Private', role: 'GPU fwd capacity provider', crush_linkage: 'Primary H100/H200 fwd crush expression; spot/fwd arb on owned fleet.', margin_note: 'Gross margin tied to rental basis vs power cost at colo sites.' },
      { name: 'Crusoe', ticker: 'Private', role: 'Energy-linked compute', crush_linkage: 'Flare-gas and Midwest-adjacent power basis directly in unit economics.', margin_note: 'Merchant power discount vs grid LMP drives crush margin uplift.' },
      { name: 'Lambda Labs', ticker: 'Private', role: 'Rental basis operator', crush_linkage: 'Spot rental index anchor; short leg of core crush (long fwd / short spot).', margin_note: 'Spot/fwd spread is primary P&L driver on inference rentals.' },
      { name: 'Applied Digital', ticker: 'APLD', role: 'Hosted GPU capacity', crush_linkage: 'Colocated HPC hosting; power pass-through on Midwest-style sites.', margin_note: 'Hosting gross margin sensitive to $/MWh and utilization.' },
      { name: 'Iris Energy', ticker: 'IREN', role: 'Energy + compute co-location', crush_linkage: 'Renewable-powered mining/compute; power basis in margin stack.', margin_note: 'Merchant power cost vs compute revenue analog to crush margin.' },
      { name: 'Fluidstack', ticker: 'Private', role: 'Regional capacity basis', crush_linkage: 'EU/US capacity spreads; deferred delivery on GPU clusters.', margin_note: 'Fwd premium capture similar to 3M/6M crush curve trades.' },
      { name: 'Vast.ai', ticker: 'Private', role: 'Spot GPU marketplace', crush_linkage: 'Spot leg price discovery; liquidity gaps widen crush spread.', margin_note: 'Thin spot book amplifies basis dislocation signals.' },
    ],
    margin_analogs: [
      { name: 'Equinix', ticker: 'EQIX', role: 'Power-intensive colocation', crush_linkage: 'Power is largest opex; Midwest hub LMP flows through to customer pricing.', margin_note: 'Gross margin compresses when merchant power rises faster than contract escalators.' },
      { name: 'Digital Realty', ticker: 'DLR', role: 'Hyperscaler lease REIT', crush_linkage: 'Triple-net leases with power pass-through clauses on AI-ready builds.', margin_note: 'Development yield sensitive to power basis and capex (copper/interconnect).' },
      { name: 'Constellation Energy', ticker: 'CEG', role: 'Midwest merchant power', crush_linkage: 'Indiana Hub / MISO exposure; nuclear + gas merchant margin.', margin_note: 'Spark spread and RT premium drive gross margin like power leg of crush.' },
      { name: 'Vistra', ticker: 'VST', role: 'Merchant generation', crush_linkage: 'MISO/ERCOT-adjacent merchant stack; summer peak margin analog.', margin_note: 'Peak RT LMP capture mirrors seasonal crush scenario (+$8/MWh).' },
      { name: 'NextEra Energy', ticker: 'NEE', role: 'Regulated + merchant mix', crush_linkage: 'Renewable PPA vs merchant shortfall; blended power cost curve.', margin_note: 'Regulated gross margin stable; merchant sleeve shows power basis beta.' },
      { name: 'CME Group', ticker: 'CME', role: 'Basis infrastructure', crush_linkage: 'BTC futures basis rails; clearing and convergence mechanics analog.', margin_note: 'Transaction margin on basis products; not crush P&L but infrastructure comp.' },
    ],
  },
};